---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "RTVXVUYNpZP8K7RDZBXeytKbvpVPRxwje8c/S93Y+RkaVl6ez/FZECzno5/HvyWJ6juNSpEjGs0CIG2z5bT9Lk9r5nLcGIOzHKe8yqPROu4HQwoCG4bsgqsSeROK+ZBz1iY4yU6JxxMPrZKA7WoOEMMbTvepedio4zyjZjR17U8="
